import yaml
import os
import sys
import datetime

def get_config(configPath):
    if not os.path.isfile(configPath):
        sys.exit(f"ERROR: File does not exist at {configPath}")
    with open(configPath, "r") as file:
        config = yaml.safe_load(file)
    return config

def get_default_parameters():
    # misc = config.get("misc", {})
    verbosity = "debug" # misc.get("verbosity", ".")
    rmsd_threshold = 1.0 # misc.get("rmsd", 2.0)
    project_name = "Kemp_eliminase" # misc.get("project_name", "test")
    workdir = "/home/mchrnwsk/prometheozyme/runs" # misc.get("workdir", ".")

    # orca
    orca = {
        "orcapath": "/home/mchrnwsk/tools/orca_6_1_1_linux_x86-64_shared_openmpi418/orca",
        "qmMethod_dock": "XTB2",
        "qmMethod_opt": "XTB2",
        "strategy": "NORMAL",
        "optLevel": "sloppyopt",
        "nOpt": 5,
        "fixHost": True,
        "gridExtent": 15,
        "nprocs": 8
    }

    # Setup output dir
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    project_name = f"{timestamp}_{project_name}"
    outdir = os.path.join(workdir, project_name)
    os.makedirs(outdir, exist_ok=True)

    return outdir, verbosity, rmsd_threshold, orca

def get_parameters(config):
        # Get miscellaneous parameters
    misc = config.get("misc", {})
    verbosity = misc.get("verbosity", ".")
    rmsd_threshold = misc.get("rmsd", 2.0)
    addTimestamp = misc.get("timestamp", True)
    project_name = misc.get("project_name", "test")
    workdir = misc.get("workdir", ".")

    # Get orca docker parameters
    orca = config.get("orca", {})

    # Setup output dir
    if addTimestamp:
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        project_name = f"{timestamp}_{project_name}"
    outdir = os.path.join(workdir, project_name)
    os.makedirs(outdir, exist_ok=True)

    # Get ingredients metadata
    ingredients = config.get("ingredients", [])

    return outdir, verbosity, rmsd_threshold, orca, ingredients

def get_cookbook(config):
    ingredients = config.get("ingredients", []) # list of dicts, keys {id: string, name: string, charge: int, multiplicity: int, file: string, atoms: list[dict{id: string, elem: string, atomId: int}]}
    flavours = config.get("flavours", []) # list of dicts, keys {id: string, name: string}
    restraints = config.get("restraints", []) # list of dicts, keys {id: string, type: string, value: float, connections: list[dict{id: string}]}
    recipes = config.get("recipes", []) # list of dicts, keys are flavour ids {id: dict{molecule: dict{id}}, atom: dict{id}}
    return ingredients, flavours, restraints, recipes

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Read configuration file.")
    parser.add_argument('--graph_config', type=str, default=None, help="Path to the configuration YAML file generated by graph-based visual scripting website.")
    args = parser.parse_args()
    if not args.graph_config:
        # TODO del static assignemnt when finished testing
        args.graph_config = "/home/mchrnwsk/prometheozyme/graph-config.json"
    graph_config = get_config(args.graph_config)
    outdir, verbosity, rmsd_threshold, orca = get_default_parameters()
    ingredients, flavours, restraints, recipes = get_cookbook(graph_config)
    print(ingredients)
